{
    'name': 'Factura modificada Rozas Y Tapados Alba',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Factura modificada para Rozas Y Tapados Alba',
    'description': """Factura modificada para Rozas Y Tapados Alba""",
    'author': 'Pymtech Solutions',
    'company': 'Pymtech Solutions',
    'maintainer': 'Pymtech Solutions',
    'depends': ['account', 'web', 'sale_management'],
    'data': ['security/ir.model.access.csv',
             'data/design_templates.xml',
             'data/normal_preview_templates.xml',
             'data/modern_preview_templates.xml',
             'data/old_standard_preview_templates.xml',
             'views/doc_layout_views.xml',
             'views/base_document_layout_views.xml',
             'views/custom_external_layout_templates.xml',
             'views/account_move_views.xml',
             'reports/normal_invoice_templates.xml',
             'reports/report_invoice_templates.xml',
             'reports/preview_layout_report_templates.xml',
             ],
    'images': ['static/description/banner.jpg'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
